### ISSUE TITLE
Discount participant list

### ISSUE THREAD

**Issue by cbruguera** [Horizon88/SelfKey#8]
"Whitelisting" feature should be implemented so that certain addresses are subject to different (discount) price rates during pre-sale or sale periods.

**Comment by Horizon88** [comment]
anything is needed to do this at this point carlos?

**Comment by cbruguera** [comment]
@Horizon88 
We only need to define this a little bit better: How many "whitelists" are we creating? what are the rates for these lists? What time restrictions do apply (some discounts could be valid only during presale, others not, etc).

Once we define this, it's just a matter of putting in the code.
